#!/bin/sh
bin/console --env=test doctrine:database:drop --force && \
bin/console --env=test doctrine:database:create && \
bin/console --env=test doctrine:schema:update --force && \
APP_DEBUG=true APP_ENV=test vendor/bin/phpunit "$@"
